### ISSUE TITLE
Statefulset's pod got stuck in terminating forever after deleting

### ISSUE THREAD

**Issue by sjtufl** [alibaba/hybridnet#406]
Bug Report
---

Type: *bug report*

### What happened

Statefulset's pod got stuck in terminating forever after deleting, and container state in the pod status shows as following

```
containerStatuses:
  image: ""
  lastState:
      terminated:
        exitCode: 137
        finishedAt: null
        message: The container could not be located when the pod was deleted.  The
          container used to be Running
        reason: ContainerStatusUnknown
        startedAt: null
  name: xxx-container
  ready: false
  restartCount: 0
  started: false
  state:
    waiting:
      reason: ContainerCreating
```

### What you expected to happen

Pod can be deleted.

### Environment
- hybridnet version: v0.8.7
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Kubernetes version:
- Install tools:
- Others:
